// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBB2sRiGNzrpPMq-so50paCUUjPHhrLJ-U',
    appId: '1:1091558965485:web:c9a21e5d126121e97e0ce4',
    messagingSenderId: '1091558965485',
    projectId: 'fooddeliveryproj-bfd24',
    authDomain: 'fooddeliveryproj-bfd24.firebaseapp.com',
    storageBucket: 'fooddeliveryproj-bfd24.firebasestorage.app',
    measurementId: 'G-YDEDK7NMWH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5gqwwNJkHEOIgnhhjssIUVObpjuDDKGI',
    appId: '1:1091558965485:android:72d16114e6dc474e7e0ce4',
    messagingSenderId: '1091558965485',
    projectId: 'fooddeliveryproj-bfd24',
    storageBucket: 'fooddeliveryproj-bfd24.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCc0ebHTjR106dg366V5nWY5eJuSDOcbhw',
    appId: '1:1091558965485:ios:ad0a205e83573b9c7e0ce4',
    messagingSenderId: '1091558965485',
    projectId: 'fooddeliveryproj-bfd24',
    storageBucket: 'fooddeliveryproj-bfd24.firebasestorage.app',
    iosBundleId: 'com.example.foodDeliveryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBB2sRiGNzrpPMq-so50paCUUjPHhrLJ-U',
    appId: '1:1091558965485:web:d1e7f7523e2800b37e0ce4',
    messagingSenderId: '1091558965485',
    projectId: 'fooddeliveryproj-bfd24',
    authDomain: 'fooddeliveryproj-bfd24.firebaseapp.com',
    storageBucket: 'fooddeliveryproj-bfd24.firebasestorage.app',
    measurementId: 'G-9FEFC76PBH',
  );
}
